name: GitHub Action 

on: 
  push:
    branches:    
      - dev
  pull_request:
    branches:    
      - main

jobs:
  deploy:
    name: GitHub Pipeline
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Selecting Xcode_Version
        run: sudo xcode-select -switch /Applications/Xcode_14.2.app
        
      - name: Running Xcode version 
        run: /usr/bin/xcodebuild -version
   
      - name: Build Cleanup
        run: |
          xcodebuild clean -project GitHub Action.xcodeproj -scheme GitHub Action | xcpretty
          
